var Postbox = {
    //SELECTED_VIEW_MESSAGE: "SELECTED_VIEW_MESSAGE",
    //SELECTED_QUERY_MESSAGE: "SELECTED_QUERY_MESSAGE",
    VALIDATION_MODEL_STATE: "VALIDATION_MODEL_STATE",
    //FAVOURITES_MODIFIED_MESSAGE: "FAVOURITES_MODIFIED_MESSAGE",

    FOOTER_ACTION_SAVE: "FOOTER_ACTION_SAVE",
    FOOTER_ACTION_SAVE_AND_NEW: "FOOTER_ACTION_SAVE_AND_NEW",
    FOOTER_ACTION_DELETE: "FOOTER_ACTION_DELETE",
    FOOTER_ACTION_CLOSE: "FOOTER_ACTION_CLOSE",


    REFRESH_READONLY_GRID: "REFRESH_READONLY_GRID",

    RETURN_VALUE_TO_COMBOBOX: "RETURN_VALUE_TO_COMBOBOX",
    
    CLEAR_VALUE_TO_COMBOBOX: "CLEAR_VALUE_TO_COMBOBOX",
    
    CHANGE_DATASOURCE_FOR_COMBOBOX: "CHANGE_DATASOURCE_FOR_COMBOBOX",
    
    CHANGE_VALUE_FOR_COMBOBOX_IN_GRID: "CHANGE_VALUE_FOR_COMBOBOX_IN_GRID",
    
    //KENDO_FORMAT_CONTROLS: "KENDO_FORMAT_CONTROLS",
    WORKCOMP_DROPDOWN_CHANGE: "WORKCOMP_DROPDOWN_CHANGE",

    SELECTED_QUERY_FILTER_APPLIED: "SELECTED_QUERY_FILTER_APPLIED",

    RETURN_VALUE_FOR_GRID: "RETURN_VALUE_FOR_GRID",


    REFRESH_VALUE_PARENT: "REFRESH_VALUE_PARENT",

    REFRESH_VALUE_PARENT_ALERT: "REFRESH_VALUE_PARENT_ALERT",

    RETURN_VALUE_FOR_FILTER: "RETURN_VALUE_FOR_FILTER",
    
    //ADVANCED_SEARCH_CRITERIA: "ADVANCED_SEARCH_CRITERIA",
    //CUSTOM_ADVANCED_SEARCH_CRITERIA: "CUSTOM_ADVANCED_SEARCH_CRITERIA",
    
    //WINDOW_RESIZE: "WINDOW_RESIZE",
    //INPUT_TIME_CHANGE: "INPUT_TIME_CHANGE",
    //RESCAN_ORGININAL_VALUES: "RESCAN_ORGININAL_VALUES"
    CLOSE_GRID_SEND_MAIL: "CLOSE_GRID_SEND_MAIL",
    CLOSE_PARENT_WINDOWS_KENDO: "CLOSE_PARENT_WINDOWS_KENDO",
    CLOSE_GRID_SEARCH_MAIL: "CLOSE_GRID_SEARCH_MAIL",
    ELEMENT_AND_DATA_WINDOW: "ELEMENT_AND_DATA_WINDOW",
    SELECT_EMAIL_DATA_ON_DUAL_GRID: "SELECT_EMAIL_DATA_ON_DUAL_GRID",
    SAVE_DIARY_WHEN_UPDATE_STATUS_CANCEL: "SAVE_DIARY_WHEN_UPDATE_STATUS_CANCEL",

};